// <auto-generated />
using System;
using AppCoroUPB.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCoroUPB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514042912_AddTablaLugaresEnsayo")]
    partial class AddTablaLugaresEnsayo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCoroUPB.Models.Ensayo", b =>
                {
                    b.Property<int>("idEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEns"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IdLugEns")
                        .HasColumnType("int");

                    b.HasKey("idEns");

                    b.ToTable("Ensayos");
                });

            modelBuilder.Entity("AppCoroUPB.Models.LugarEnsayo", b =>
                {
                    b.Property<int>("idLugEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLugEns"));

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLugEns");

                    b.ToTable("LugaresEnsayo");
                });
#pragma warning restore 612, 618
        }
    }
}
