// <auto-generated />
using System;
using AppCoroUPB.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCoroUPB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521214545_AddSprintTwo")]
    partial class AddSprintTwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCoroUPB.Models.Cancion", b =>
                {
                    b.Property<int>("idCanc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCanc"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idClasif")
                        .HasColumnType("int");

                    b.Property<int>("idComp")
                        .HasColumnType("int");

                    b.Property<int>("idIdioma")
                        .HasColumnType("int");

                    b.HasKey("idCanc");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Carrera_Dependencia", b =>
                {
                    b.Property<int>("idCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCarrera"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCarrera");

                    b.ToTable("Carrera_Dependencia");
                });

            modelBuilder.Entity("AppCoroUPB.Models.ClasificacionCancion", b =>
                {
                    b.Property<int>("idClasif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idClasif"));

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idClasif");

                    b.ToTable("ClasificacionCancion");
                });

            modelBuilder.Entity("AppCoroUPB.Models.ClasificacionVoz", b =>
                {
                    b.Property<int>("idVoz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVoz"));

                    b.Property<string>("Voz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVoz");

                    b.ToTable("ClasificacionVoz");
                });

            modelBuilder.Entity("AppCoroUPB.Models.CompositorCancion", b =>
                {
                    b.Property<int>("idComp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idComp"));

                    b.Property<string>("Compositor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idComp");

                    b.ToTable("CompositorCanciones");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Director", b =>
                {
                    b.Property<int>("idDic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDic"));

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idEstado")
                        .HasColumnType("int");

                    b.HasKey("idDic");

                    b.ToTable("Directores");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Ensayo", b =>
                {
                    b.Property<int>("idEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEns"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IdLugEns")
                        .HasColumnType("int");

                    b.HasKey("idEns");

                    b.ToTable("Ensayos");
                });

            modelBuilder.Entity("AppCoroUPB.Models.EstadoInt", b =>
                {
                    b.Property<int>("idEst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEst"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEst");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Idioma", b =>
                {
                    b.Property<int>("idIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idIdioma"));

                    b.Property<string>("idioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idIdioma");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Integrante", b =>
                {
                    b.Property<int>("idInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInt"));

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdVoz")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCarrera")
                        .HasColumnType("int");

                    b.Property<int>("idVinculo")
                        .HasColumnType("int");

                    b.HasKey("idInt");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("AppCoroUPB.Models.LugarEnsayo", b =>
                {
                    b.Property<int>("idLugEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLugEns"));

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLugEns");

                    b.ToTable("LugaresEnsayo");
                });

            modelBuilder.Entity("AppCoroUPB.Models.LugarPresentacion", b =>
                {
                    b.Property<int>("idLugPresent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLugPresent"));

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLugPresent");

                    b.ToTable("LugaresPresentaciones");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Presentacion", b =>
                {
                    b.Property<int>("idPresent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPresent"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("idEvent")
                        .HasColumnType("int");

                    b.Property<int>("idLugPresent")
                        .HasColumnType("int");

                    b.HasKey("idPresent");

                    b.ToTable("Presentaciones");
                });

            modelBuilder.Entity("AppCoroUPB.Models.TipoEvento", b =>
                {
                    b.Property<int>("idEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEvent"));

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEvent");

                    b.ToTable("TipoEvento");
                });

            modelBuilder.Entity("AppCoroUPB.Models.TipoVinculo", b =>
                {
                    b.Property<int>("idVinculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVinculo"));

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVinculo");

                    b.ToTable("TipoVinculo");
                });
#pragma warning restore 612, 618
        }
    }
}
