// <auto-generated />
using System;
using AppCoroUPB.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCoroUPB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCoroUPB.Models.Carrera_Dependencia", b =>
                {
                    b.Property<int>("idCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCarrera"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCarrera");

                    b.ToTable("Carrera_Dependencia");
                });

            modelBuilder.Entity("AppCoroUPB.Models.ClasificacionVoz", b =>
                {
                    b.Property<int>("idVoz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVoz"));

                    b.Property<string>("Voz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVoz");

                    b.ToTable("ClasificacionVoz");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Ensayo", b =>
                {
                    b.Property<int>("idEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEns"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IdLugEns")
                        .HasColumnType("int");

                    b.HasKey("idEns");

                    b.ToTable("Ensayos");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Estado", b =>
                {
                    b.Property<int>("idEst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEst"));

                    b.Property<string>("EstadoInt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEst");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("AppCoroUPB.Models.Integrante", b =>
                {
                    b.Property<int>("idInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInt"));

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdVoz")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCarrera")
                        .HasColumnType("int");

                    b.Property<int>("idVinculo")
                        .HasColumnType("int");

                    b.HasKey("idInt");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("AppCoroUPB.Models.LugarEnsayo", b =>
                {
                    b.Property<int>("idLugEns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLugEns"));

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLugEns");

                    b.ToTable("LugaresEnsayo");
                });

            modelBuilder.Entity("AppCoroUPB.Models.TipoVinculo", b =>
                {
                    b.Property<int>("idVinculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVinculo"));

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVinculo");

                    b.ToTable("TipoVinculo");
                });
#pragma warning restore 612, 618
        }
    }
}
